### ISSUE TITLE
elynx-markov-0.5.1.0 markov-test:  exited with: ExitFailure 1 

### ISSUE THREAD

**Issue by juhp** [dschrempf/elynx#2] opened 2021-06-14 10:16 UTC
The testsuite is failing the current Stackage Nightly build:

```
Test suite failure for package elynx-markov-0.5.1.0                                                                   [38/193233]
    markov-test:  exited with: ExitFailure 1                                                                                     
                                                                                 
    ELynx.Data.MarkovProcess.AminoAcid                                                                                           
      statDistLG                                                                                                                 
        matches distribution from python library                                                                                 
      exchLG                                                                                                                     
        matches exchangeability matrix from python library                                                                       
      lg                                                                                                                         
        stationary distribution can be extracted                                                                                 
      lgCustom                                                                                                                   
        stationary distribution can be recovered                                                                                 
      poisson                                                                                                                    
        stationary distribution is uniform 1/20                                                                                  
      poissonCustom                                                                                                              
        stationary distribution can be recovered                                                                                 
    ELynx.Data.MarkovProcess.Nucleotide                                                                                          
      getStationaryDistribution                                                                                                  
        extracts the stationary distribution from a rate matrix                                                                  
    ELynx.Data.MarkovProcess.RateMatrix
      exchFromListLower
        correctly converts to matrix from list
      exchFromListUpper
        correctly converts to matrix from list
    ELynx.Import.MarkovProcess.EDMModelPhylobayes
      phylobayes
        parses a text file with stationary distributions in phylobayes format
    ELynx.Import.MarkovProcess.SiteprofilesPhylobayes
      import phylobayes siteprofiles
        parses a text file with siteprofiles in phylobayes format
    ELynx.Simulate.MarkovProcessAlongTree
      simulateNSitesAlongTree
        simulates one site along an easy tree FAILED [1]
        simulates some sites along a harder tree
     
    Failures:
     
      test/ELynx/Simulate/MarkovProcessAlongTreeSpec.hs:47:5: 
      1) ELynx.Simulate.MarkovProcessAlongTree.simulateNSitesAlongTree simulates one site along an easy tree
           expected: Node {rootLabel = 0, subForest = []}
            but got: Node {rootLabel = 2, subForest = []}
     
      To rerun use: --match "/ELynx.Simulate.MarkovProcessAlongTree/simulateNSitesAlongTree/simulates one site along an easy tree
/"
     
    Randomized with seed 1066746489
     
    Finished in 0.1092 seconds
    13 examples, 1 failure
```

**Comment by dschrempf** [comment] 2021-06-14 12:52
This must have been caused by an internal change in mwc-random, because the result for a computation has changed for the same seed value. Should be fixed in 0.5.1.1. Thank you!

**Closed as completed by dschrempf** 2021-06-14 12:52 UTC
